version: '3'

services:
  database:
    container_name: database
    build: ./database
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "go_practice"
